export const nawiriBrand = {
  companyName: 'Nawiri Hair Kenya',
  shortName: 'Nawiri Hair',
  motto: 'Blending quality, class, and affordability.',
  logo: '/images/nawiri_logo.jpeg',
  businessCard: '/images/Nawiri card.jpeg',
  phoneDisplay: '0703 862 741',
  phoneDial: '+254703862741',
  email: 'nawirihairke@gmail.com',
  location: 'Mithoo Business Centre, Moi Ave',
  instagramHandle: '@nawiri_hairke',
  tiktokHandle: '@nawiri_hairke',
  instagramUrl: 'https://www.instagram.com/nawiri_hairke/',
  tiktokUrl: 'https://www.tiktok.com/@nawiri_hairke',
  whatsappUrl: 'https://wa.me/254703862741',
  websiteUrl: 'https://nawirihairke.com',
};
