import { saveAs } from 'file-saver';
import { jsPDF } from 'jspdf';
import * as XLSX from 'xlsx';

// Export to Excel
const exportToExcel = (data, filename = 'products') => {
  const worksheet = XLSX.utils.json_to_sheet(data);
  const workbook = XLSX.utils.book_new();
  XLSX.utils.book_append_sheet(workbook, worksheet, 'Products');

  // Create Excel buffer
  const excelBuffer = XLSX.write(workbook, { bookType: 'xlsx', type: 'array' });
  const blob = new Blob([excelBuffer], { type: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet' });

  saveAs(blob, `${filename}.xlsx`);
};

// Export to CSV
const exportToCSV = (data, filename = 'products') => {
  const worksheet = XLSX.utils.json_to_sheet(data);
  const csv = XLSX.utils.sheet_to_csv(worksheet);
  const blob = new Blob([csv], { type: 'text/csv;charset=utf-8;' });

  saveAs(blob, `${filename}.csv`);
};

// Export to PDF using jsPDF (manual table — no autoTable plugin required)
const exportToPDF = (data, filename = 'products') => {
  const doc = new jsPDF({ orientation: 'landscape' });

  doc.setFontSize(16);
  doc.setTextColor(41, 128, 185);
  doc.text('Product Data Export', 14, 16);
  doc.setFontSize(9);
  doc.setTextColor(120);
  doc.text(`Generated by Taji Cart AI — ${new Date().toLocaleString()}`, 14, 22);

  const headers = ['Name', 'SKU', 'Price (Ksh)', 'Stock', 'Category', 'Description'];
  const colWidths = [50, 25, 25, 18, 35, 120];
  const startX = 14;
  let y = 30;
  const rowHeight = 7;

  // Header row
  doc.setFillColor(41, 128, 185);
  doc.setTextColor(255);
  doc.setFontSize(9);
  doc.setFont(undefined, 'bold');
  let x = startX;
  headers.forEach((h, i) => {
    doc.rect(x, y, colWidths[i], rowHeight, 'F');
    doc.text(h, x + 2, y + 5);
    x += colWidths[i];
  });
  y += rowHeight;

  // Data rows
  doc.setFont(undefined, 'normal');
  data.forEach((product, idx) => {
    if (y > 190) {
      doc.addPage();
      y = 14;
    }
    const row = [
      product.name || '',
      product.sku || '',
      product.price != null ? String(Number(product.price).toFixed(2)) : '',
      String(product.stock || ''),
      product.category || '',
      product.description || '',
    ];
    doc.setFillColor(idx % 2 === 0 ? 245 : 255, idx % 2 === 0 ? 245 : 255, idx % 2 === 0 ? 245 : 255);
    doc.setTextColor(40);
    x = startX;
    row.forEach((cell, i) => {
      doc.rect(x, y, colWidths[i], rowHeight, 'F');
      doc.setDrawColor(220);
      doc.rect(x, y, colWidths[i], rowHeight, 'S');
      const truncated = doc.splitTextToSize(String(cell), colWidths[i] - 4)[0] || '';
      doc.text(truncated, x + 2, y + 5);
      x += colWidths[i];
    });
    y += rowHeight;
  });

  // Page numbers
  const pageCount = doc.internal.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(150);
    doc.text(`Page ${i} of ${pageCount}`, doc.internal.pageSize.getWidth() - 30, doc.internal.pageSize.getHeight() - 8);
  }

  doc.save(`${filename}.pdf`);
};

// Export to Word (DOCX) - simplified version using HTML
const exportToWord = (data, filename = 'products') => {
  // Create HTML content
  let htmlContent = `
    <!DOCTYPE html>
    <html>
    <head>
      <meta charset="UTF-8">
      <title>Product Data Export</title>
      <style>
        body { font-family: Arial, sans-serif; }
        h1 { color: #2980b9; }
        table { border-collapse: collapse; width: 100%; margin-top: 20px; }
        th { background-color: #2980b9; color: white; padding: 10px; text-align: left; }
        td { border: 1px solid #ddd; padding: 8px; }
        tr:nth-child(even) { background-color: #f2f2f2; }
      </style>
    </head>
    <body>
      <h1>Product Data Export</h1>
      <table>
        <thead>
          <tr>
            <th>Name</th>
            <th>SKU</th>
            <th>Price</th>
            <th>Stock</th>
            <th>Category</th>
            <th>Description</th>
          </tr>
        </thead>
        <tbody>
  `;

  data.forEach(product => {
    const categoryText = Array.isArray(product.category)
      ? product.category.join(', ')
      : (product.category || '');

    htmlContent += `
          <tr>
            <td>${product.name || ''}</td>
            <td>${product.sku || ''}</td>
            <td>${product.price ? `Ksh ${product.price.toFixed(2)}` : ''}</td>
            <td>${product.stock || ''}</td>
            <td>${categoryText}</td>
            <td>${product.description || ''}</td>
          </tr>
    `;
  });

  htmlContent += `
        </tbody>
      </table>
      <p style="margin-top: 30px; font-size: 12px; color: #666;">
        Generated by Taji Cart AI - ${new Date().toLocaleString()}
      </p>
    </body>
    </html>
  `;

  // Create blob and download
  const blob = new Blob(['\ufeff', htmlContent], {
    type: 'application/msword;charset=utf-8;'
  });

  saveAs(blob, `${filename}.doc`);
};

// Export to JSON
const exportToJSON = (data, filename = 'products') => {
  const blob = new Blob([JSON.stringify(data, null, 2)], { type: 'application/json' });
  saveAs(blob, `${filename}.json`);
};

export {
  exportToExcel,
  exportToCSV,
  exportToPDF,
  exportToWord,
  exportToJSON
};